### ISSUE TITLE
some questions about the project structure and howw to understand each component

### ISSUE THREAD

**Issue by Hezhexi2002** [DavidGillsjo/VideoIMUCapture-Android#11]
@DavidGillsjo Hi,I'm very excited to find your project here because I'm currently working on testing vins-mono and orb slam3 on my own android phone,I have tried [Android_Camera-IMU](https://github.com/hitcm/Android_Camera-IMU) and [android_ros_sensors](https://github.com/huaibovip/android_ros_sensors) these two project to record the rosbag of my camera and imu,However,both of them have some problems where the timestamp between the cam and imu recored by the first project are not aligned and the image size is 1920*1080 recored by the second project which means you have to resize the image and re-calibrate the camera in the corresponding size.Fortunately,I find your project when I was browsing this [blog](https://www.jianshu.com/p/f715ce9937d9),I have install the latest apk
and clone the source code locally.I noticed that there is a hooks directory which have three shell scripts：
![image](https://user-images.githubusercontent.com/53631206/215981515-aeb3cc8e-3ed4-4450-817e-80bc683b4fe3.png)
and I also found that in the `run_dockerhub.sh` and `build_docker.sh` you directly use the three scripts：
![image](https://user-images.githubusercontent.com/53631206/215982881-c1779f35-5fbe-454f-819d-d06ebccf57d9.png)
![image](https://user-images.githubusercontent.com/53631206/215982927-c570bc31-aa81-4135-8b94-81c257a6226e.png)
but the libs directory is empty,so how could you build the container finally?and I have install kalibr through docker before on my machine,so is this means I don't need to use the script to build the container again?Looking forward to your comment!:-)

**Comment by DavidGillsjo** [comment]
Hi,
I'm glad the project may be of help to you! 
If you do not want to build the docker image there is also an option to use `run_dockerhub.sh` to use the pre-built image from dockerhub. This image already contains the compiled protobuf python lib and kalibr.

However, if you for some reason need to build the image yourself I'll try to answer your questions.
1. The hook scripts are used by dockerhub when building the image. 
2. The `libs` folder is probably empty because you have not pulled the submodules using `git submodule init && git submodule update`
3. If you run this docker image and want to use your own `kalibr` you will have to link it into the docker container. Each docker container is a separate environment so this docker container will not know anything about your previous `kalibr` docker image. The version of `kalibr` in `libs` is a fork by me where I patched a feature to make it work for my data. It may very well now be on the master branch of `kalibr` but I haven't tried it.

Just let me know if you have further questions.

**Comment by Hezhexi2002** [comment]
> Hi, I'm glad the project may be of help to you! If you do not want to build the docker image there is also an option to use `run_dockerhub.sh` to use the pre-built image from dockerhub. This image already contains the compiled protobuf python lib and kalibr.
> 
> However, if you for some reason need to build the image yourself I'll try to answer your questions.
> 
> 1. The hook scripts are used by dockerhub when building the image.
> 2. The `libs` folder is probably empty because you have not pulled the submodules using `git submodule init && git submodule update`
> 3. If you run this docker image and want to use your own `kalibr` you will have to link it into the docker container. Each docker container is a separate environment so this docker container will not know anything about your previous `kalibr` docker image. The version of `kalibr` in `libs` is a fork by me where I patched a feature to make it work for my data. It may very well now be on the master branch of `kalibr` but I haven't tried it.
> 
> Just let me know if you have further questions.

OK,thanks for your detailed reply,Actually I have figured out why the `libs` folder is empty at first later because in [run_dockerhub.sh](https://github.com/DavidGillsjo/VideoIMUCapture-Android/blob/master/calibration/run_dockerhub.sh) you run the `./hooks/pre_run` which actually is pulling the submodules needed to build the container.Besides,I'd like to use your image to run through the whole process and later I maybe run with my `kalibr` image and see if it works too.And I will give you more feedback as soon as there is any questions afterwards,really thanks for your patience again!:-)

**Comment by DavidGillsjo** [comment]
Great! Feel free to re-open the issue if more questions arise.

**Comment by Hezhexi2002** [comment]
> Great! Feel free to re-open the issue if more questions arise.

Hi,I have successfully build the container afterwards but it throws a error when I attempt to run the `python data2statistics.py /host_home/<path-to-recording>/video_meta.pb3` to look for `intrinsic_params` and `distortion_params`：
![image](https://user-images.githubusercontent.com/53631206/216020860-85d3b3ab-bc57-4383-b351-c5bbbc6e92cb.png)
it seems about the privileges setting when build the container but I have no idea to solve that,could you please give me some suggestions?

**Comment by Hezhexi2002** [comment]
> Great! Feel free to re-open the issue if more questions arise.

Hi,I have successfully build the container afterwards but it throws a error when I attempt to run the `python data2statistics.py /host_home/<path-to-recording>/video_meta.pb3` to look for `intrinsic_params` and `distortion_params`：
![image](https://user-images.githubusercontent.com/53631206/216020860-85d3b3ab-bc57-4383-b351-c5bbbc6e92cb.png)
it seems about the privileges setting when build the container but I have no idea to solve that,could you please give me some suggestions?

**Comment by DavidGillsjo** [comment]
Interesting, it seems to not locate your user ID correctly.  Try calling the docker run as
```
DUSER=matrix SUDO=1 DATA=<datapath> ./run_dockerhub.sh
```
Also, have you tried running the script without being sudo user?
Just `python data2stat....` Or is sudo required to access the folder you mounted to `data`?

**Comment by Hezhexi2002** [comment]
> Interesting, it seems to not locate your user ID correctly. Try calling the docker run as
> 
> ```
> DUSER=matrix SUDO=1 DATA=<datapath> ./run_dockerhub.sh
> ```
> 
> Also, have you tried running the script without being sudo user? Just `python data2stat....` Or is sudo required to access the folder you mounted to `data`?

Actually I use  `python data2statistics.py ` without sudo at first which will output this error：
![image](https://user-images.githubusercontent.com/53631206/216052518-9690ba7a-2de5-406a-9c53-d626b47a16ef.png)
then I began to run it again with sudo and the error has been shown in my last post,I also try the `DUSER=matrix SUDO=1 DATA=<datapath> ./run_dockerhub.sh` you mentioned but the error still exits:
![image](https://user-images.githubusercontent.com/53631206/216053652-69bb4b04-86ac-46e7-9a0c-08efd3442e83.png)
so I guess whether this is due to there is something wrong in the `libs/dockers/common/run.sh` because I see you call it in the run_dockerhub.sh but I'm sure exactly which part is going wrong:-(

**Comment by DavidGillsjo** [comment]
OK, so the problem is that the docker container cannot map your uid to a user. 
Most likely I build this image on my computer which does not have a user id 1000. 

I updated the docker script, so please pull from master again and see if it works.
If not, you may have to build the image locally.

**Comment by nowhereman1999** [comment]
> OK, so the problem is that the docker container cannot map your uid to a user. Most likely I build this image on my computer which does not have a user id 1000.
> 
> I updated the docker script, so please pull from master again and see if it works. If not, you may have to build the image locally.

Oh,it works now after I pull from the master again:
![image](https://user-images.githubusercontent.com/53631206/216071494-12c8f8e5-383d-4e2f-9a9b-ac27914136da.png)
I check the modification you have made just a few minutes before and found that you delete the line `-v "/etc/passwd:/etc/passwd:ro"\`:
![image](https://user-images.githubusercontent.com/53631206/216071722-81c7e99c-c50c-4b2d-8ee7-be73437be7f7.png)
so is this the culprit which prevents the docker container mapping my uid to a user?I also check the [Dockerfile](https://github.com/DavidGillsjo/VideoIMUCapture-Android/blob/master/calibration/Dockerfile) you provide in the repo,the patched feature you mentioed before seems like that is you add the single camera calibration support for kalibr by modifying the `MulticamGraph.py`,However,the latest kalibr have already integrated the support for single camera calibration,so I think the `kalibr` I built with the official [Dockerfile_ros1_20_04](https://github.com/ethz-asl/kalibr/blob/master/Dockerfile_ros1_20_04) should work too as long as I compile the proto and install some python packages in the container,I'm not sure if my understanding is correct, I hope you can point out the mistakes and give pointers:-)

**Comment by DavidGillsjo** [comment]
Actually I added the line which mount the file `/etc/passwd` from your host system. Great that it works, it will certainly help future users.

Yes, I remember it having to do with single camera support. If that is patched in kalibr then, as you say, there shouldn't be any problem using their docker and compiling the proto-lib separately.

**Comment by nowhereman1999** [comment]
> Actually I added the line which mount the file `/etc/passwd` from your host system. Great that it works, it will certainly help future users.
> 
> Yes, I remember it having to do with single camera support. If that is patched in kalibr then, as you say, there shouldn't be any problem using their docker and compiling the proto-lib separately.

oh sorry I misread the line you added,I thought you have just deleted that line,but I have some more questions about the data recorded with your apk,the first is that I want to know if the timestamp of the camera and imu data recorded by the apk is aligned because the vslam algorithms like vins or orb slam series both required the timestamp of camera and imu is synchronized or initializations of them is likely to fail;the second question is that I want to know if your project could be used to calibrate the normal usb-cam or industrial camera like [this](https://www.mindvision.com.cn/cpzx/info_62.aspx?itemid=4595&parent&lcid=101),I noticed that the data of camera and imu recored by the apk is stored toghther as protobuf file,but with the  normal usb-cam or industrial camera I can only recored the video not include the data of imu,so is there a possiablity to use your project calibrate the normal usb-cam or industrial camera?I'd appreciated it if you could give more advice!:-)

**Comment by DavidGillsjo** [comment]
**If the timestamp of the camera and imu data recorded by the apk is aligned**
It depends on the device. Most devices seems to have synchronized clocks between IMU and camera. 
We record this [here](https://github.com/DavidGillsjo/VideoIMUCapture-Android/blob/721f62d9585f7b8663a21d10c6d56cd95f30bdcd/protobuf/recording.proto#L33) in the protobuf file as `camera_meta.timestamp_source`. Still, there may be an offset due to exposure times and implementation details in the capture, but this offset is estimated by `kalibr`.

**If your project could be used to calibrate the normal usb-cam or industrial camera like this**
This projects main contributions are:
1. Android application for synchronized capture of video and IMU data to a protobuf file.
2. Reader and wrapper scripts to calibrate with `kalibr` or export the data to rosbag.

So if you only need to calibrate the distortion and intrinsic parameters for a camera I would recommend using `kalibr` directly. It only requires some images of a checkerboard in different viewing directions and is easier than calibrating camera and IMU together.

**Comment by nowhereman1999** [comment]
> **If the timestamp of the camera and imu data recorded by the apk is aligned** It depends on the device. Most devices seems to have synchronized clocks between IMU and camera. We record this [here](https://github.com/DavidGillsjo/VideoIMUCapture-Android/blob/721f62d9585f7b8663a21d10c6d56cd95f30bdcd/protobuf/recording.proto#L33) in the protobuf file as `camera_meta.timestamp_source`. Still, there may be an offset due to exposure times and implementation details in the capture, but this offset is estimated by `kalibr`.
> 
> **If your project could be used to calibrate the normal usb-cam or industrial camera like this** This projects main contributions are:
> 
> 1. Android application for synchronized capture of video and IMU data to a protobuf file.
> 2. Reader and wrapper scripts to calibrate with `kalibr` or export the data to rosbag.
> 
> So if you only need to calibrate the distortion and intrinsic parameters for a camera I would recommend using `kalibr` directly. It only requires some images of a checkerboard in different viewing directions and is easier than calibrating camera and IMU together.

OK,really thanks for your patient reply again.For your first answer which you say that you record this [here](https://github.com/DavidGillsjo/VideoIMUCapture-Android/blob/721f62d9585f7b8663a21d10c6d56cd95f30bdcd/protobuf/recording.proto#L33) but I'm still confused with what is meaning of 6 in the line   `TimestampSource timestamp_source = 6;`,is that a parameter priority or measurement precision of the timestamp source?And for the second answer,maybe I didn't  express my questions clearly yesterday,I can indeed calibrate the usb-cam and industrial camera directly using `kalibr` but the keypoint is that I want to use your project to generate the rosbag include the data of camera and imu to test the algorithms like vins and orb slam,I used to run these algorithms in tum datasets so now I want to test them in my custom scene,but `kalibr` seems not to provide the feature to convert the video recored by usb-cam or industrial camera into rosbag, so is there another possible way to make the rosbag through usb-cam or industrial camera?

**Comment by DavidGillsjo** [comment]
The `TimestampSource timestamp_source = 6` implies that there is a record in the recording named `timestamp_source` of the type `TimestampSource`. The digit is just a unique identifier that we may ignore in this context. The value of this comes from the Camera2 API enum [SENSOR_INFO_TIMESTAMP_SOURCE](https://developer.android.com/reference/android/hardware/camera2/CameraCharacteristics#SENSOR_INFO_TIMESTAMP_SOURCE). 

OK, I'm not sure I understand your setup. But in case you have a separate USB-camera and separate IMU and store this data in the same way my app stores the data, then sure you can use my scripts for the conversion. I'm not sure this will be easier than to write a small ROS-application using standard ROS nodes like [cv_camera](http://wiki.ros.org/cv_camera) and then record a rosbag using the build in command line tools.

**Comment by nowhereman1999** [comment]
> The `TimestampSource timestamp_source = 6` implies that there is a record in the recording named `timestamp_source` of the type `TimestampSource`. The digit is just a unique identifier that we may ignore in this context. The value of this comes from the Camera2 API enum [SENSOR_INFO_TIMESTAMP_SOURCE](https://developer.android.com/reference/android/hardware/camera2/CameraCharacteristics#SENSOR_INFO_TIMESTAMP_SOURCE).
> 
> OK, I'm not sure I understand your setup. But in case you have a separate USB-camera and separate IMU and store this data in the same way my app stores the data, then sure you can use my scripts for the conversion. I'm not sure this will be easier than to write a small ROS-application using standard ROS nodes like [cv_camera](http://wiki.ros.org/cv_camera) and then record a rosbag using the build in command line tools.

OK,I think I probably understand what you mean.Besides,I have made a little changes to the `libs/dockers/common/run.sh` and submitted a pr to your [dockers](https://github.com/DavidGillsjo/dockers) but I'm not sure if the step is correct because I'm not familiar with how to pull a request before,you can contact me here if there is any problem with my pr.Finally,thank you again for the detailed guidance you have given me in the past two days,and I have learned a lot of new things from it!:-)

Best regards!

**Comment by DavidGillsjo** [comment]
Thanks, good luck with your project!
