### ISSUE TITLE
time synchronization problem

### ISSUE THREAD

**Issue by XiaoyangSun22** [DavidGillsjo/VideoIMUCapture-Android#2]
Hi,I have tried your code.  I collected data by the mobile phone, and then convert the proto file into a bag file. Can you tell me whether the image IMU time in the bag file is synchronized？ Thank you in advance.

**Comment by DavidGillsjo** [comment]
Hi,
According to the Android documentation it should be synchronized if your phone supports it. 
See [this link](https://developer.android.com/reference/android/hardware/camera2/CameraCharacteristics#SENSOR_INFO_TIMESTAMP_SOURCE). This information is also included in the proto file [here](https://github.com/DavidGillsjo/VideoIMUCapture-Android/blob/364099f29a5d80ce4444790ca6af6270aa14ead2/protobuf/recording.proto#L33).

When I do calibration with Kalibr it typically estimates an offset around 20ms between IMU and Camera.
I can't say I understand why since I typically have an exposure time around 10ms, but I haven't managed to debug where the offset comes from.

Best regards,
David
