### ISSUE TITLE
"Cannot find IMU" error on Samsung A50, Android 11

### ISSUE THREAD

**Issue by pvn-jio** [DavidGillsjo/VideoIMUCapture-Android#3]
Hi,
I have been trying to use the app but I get a warning sign with "Cannot find IMU" as the error. I can understand that the issue is the SensorManager not being able to find the accelerometer and gyroscope on my phone, but I can't figure out how to enable them for this app. I'm able to use my sensors on the marslogger app (but it has different issues). I'm also able to use this app on another model with the same Android version.

Need some pointers on how to fix this.

Phone details:
Model: Samsung A50 (SM-A505F)
Android version: Android 11

**Comment by DavidGillsjo** [comment]
Hi,
Sorry to hear you're having trouble with the app. It is unfortunately untested on many devices, since I only use it on my Pixel phones.

Compared to the Marslogger I use the Uncalibrated devices for accelerometer and gyro.
Maybe these are not available on your Samsung?

Try changing the sensortypes in the Sensormanager function [setSensorType](https://github.com/DavidGillsjo/VideoIMUCapture-Android/blob/364099f29a5d80ce4444790ca6af6270aa14ead2/android_app/app/src/main/java/se/lth/math/videoimucapture/IMUManager.java#L81) to
```
ACC_TYPE = Sensor.TYPE_ACCELEROMETER;
GYRO_TYPE = Sensor.TYPE_GYROSCOPE;
```
