### ISSUE TITLE
Recording has fewer frame metadata messages than there are image frames.

### ISSUE THREAD

**Issue by BillThePlatypus** [DavidGillsjo/VideoIMUCapture-Android#4]
First off, thank you for this software. I expect this to be super useful.

I just did a quick test and I'm not having any difficulties reading the data from the protobuf file. The created mp4 file has 1,464 frames in it, but the protobuf file only has 1,456 VideoFrameMetaData messages in it, with  the frame number ranging from 2 to 1,458. Can I assume that the frame numbers are correct? If so are they zero-indexed or one-indexed? If not, how can I be certain which frame goes with which metadata?

Thanks.

**Comment by DavidGillsjo** [comment]
Thanks, I'm glad if it might be useful to someone else.

The frame numbers are zero indexed and I have not observed this issue myself. Though it is theoretically possible since there is no synchronization between the camera-, video- and proto-recording threads during start and stop of the recording. They are simply started/stopped in correct order. If I understand you correctly you are not loosing VideoFrameMetaData messages in the middle of the stream, so that is good.

You may assume the frame numbers to be correct. The protobuf writer receives messages from both the camera thread and the video encoder thread. The camera thread sends the image meta-data (including time stamp) and the encoder thread sends frame number of the video and time stamp of the image capture. So the protobuf writer pairs the image meta data with the video frame number according to the image capture timestamp.

I just updated [`data2rosbag.py`](../blob/master/calibration/data2rosbag.py) to take missing frames into account. Please let me know if you find any other tool that assumes an equal amount of video frames and VideoFrameMetaData messages.

**Comment by BillThePlatypus** [comment]
Thanks! That answers my questions. I should mention for future reference that this was done on a Pixel 4, which I believe has synchronized IMU / video.
