### ISSUE TITLE
time system

### ISSUE THREAD

**Issue by CyanInkLinmo** [DavidGillsjo/VideoIMUCapture-Android#6]
Hi,I have tried your code, it help me a lot thanks! i want know which time system used in this app. After I used data2lth_version.py, there is a attribute about time. is its unit ns? and which time system is used? thanks very much!

**Comment by DavidGillsjo** [comment]
Hi,
The time is in ns, that is correct. 
It is not absolute time, only relative. For absolute time see the `time` variable in the [VideoCaptureData](https://github.com/DavidGillsjo/VideoIMUCapture-Android/blob/48f5f7751c0dcb984bb8c4f485913d39ce33b03b/protobuf/recording.proto#L106) message from the protobuf output. It will be according to the smartphone local timezone. 

I hope that answers you question.

Best regards,
David

**Comment by CyanInkLinmo** [comment]
thanks for the answer! 
After I search for some infomation about proto and "google.protobuf.Timestamp", There are stills some point I am not sure.

 Is the time of the APP output. pd3 file relative time? i thank the file recording.propot only use to read the .pd3 file and not change  absolute time to relative. So i wanna know how APP get the absolute time and the algorithm that change absolute to relative, I can't find this in the source code file. 

thanks for your patience.

**Comment by DavidGillsjo** [comment]
Could you explain your use case? Not sure I understand your question.
The current code use 2 time sources:
- At the start of the recording, the current world time is captured using [currentTimeMillis](https://developer.android.com/reference/java/lang/System#currentTimeMillis()) which is converted to a date-time format and stored as `time` in [VideoCaptureData](https://github.com/DavidGillsjo/VideoIMUCapture-Android/blob/48f5f7751c0dcb984bb8c4f485913d39ce33b03b/protobuf/recording.proto#L106).
- For each camera frame we store a timestamp as `time_ns` in [VideoFrameMetaData](https://github.com/DavidGillsjo/VideoIMUCapture-Android/blob/48f5f7751c0dcb984bb8c4f485913d39ce33b03b/protobuf/recording.proto#L60) which is nano-seconds since boot. As long as your Android device supports it, see [SENSOR_INFO_TIMESTAMP_SOURCE_REALTIME](https://developer.android.com/reference/android/hardware/camera2/CameraMetadata#SENSOR_INFO_TIMESTAMP_SOURCE_REALTIME). The value of this is also stored in the protobuf file [here](https://github.com/DavidGillsjo/VideoIMUCapture-Android/blob/48f5f7751c0dcb984bb8c4f485913d39ce33b03b/protobuf/recording.proto#L33).

So in case you need the exact world time for each image you have to calculate the offset between the world time given by `currentTimeMillis` and the time since reboot given by `elapsedRealTimeNanos`, which is not done in the current code. 
See [here](https://developer.android.com/reference/android/os/SystemClock) for more on time functions.

You may however approximate the offset by using the world time of the start of the recording `VideoCaptureData.time` and the timestamp of the first video frame `VideoCaptureData.video_meta[0].time_ns`. The error will then be the time between the start of the recording thread and the start of camera capture, which will depend on the device. I'm guessing anything from a few ms to 1 second, but this is just a wild guess, I haven't tested the delay.

It may be worth checking the first timestamp of the IMU instead, since this should be quicker to start and has a higher sampling frequency. Then you want to check `VideoCaptureData.imu[0].time_ns` instead.

**Comment by CyanInkLinmo** [comment]
I plan to intergrate with gnss so I may need a absolute time. 
I think my problem is solved, thanks a lot for your answer!
Thanks!

**Comment by DavidGillsjo** [comment]
Good luck with your project!
