### ISSUE TITLE
Skipped Frame，Missing Data

### ISSUE THREAD

**Issue by JustC0deIt** [DavidGillsjo/VideoIMUCapture-Android#7]
First off, thank you for this software. I expect this to be super useful.

After recording the video by using Android app, i run "data2statistics.py <datafolder>/<datetime>/video_meta.pb3".Then when i run"python data2kalibr.py'" it print "skipping frame xxx,missing data".I don't know the reason,by the way,when i use the app,it warning"OIS is enabled but OIS data is not stored" and i can't enable the OIS data or close "Enable OIS".

**Comment by DavidGillsjo** [comment]
Hi,

I'm glad it may be of help.
I took a look at the code and saw that `data2rosbag.py` (used by `data2kalibr.py`) does not correctly support missing meta data. It only worked if the data was missing in the beginning of the stream. I have pushed a fix to the `master` branch and uploaded a new calibration docker image. Please try it and let me know if it works or not.

The fact that you had missing data during the stream might be due to high load in the CPU or slow writing speed (if using SD card). With the new code you should be able to see if you have many frames missing. You may also use `data2statistics.py` to see the timestamp difference between the recorded meta frames to visualize the problem.

Regarding the warning it seems that your Android device does not support management of the OIS feature through the Android Camera2 API. I've found that this is common in Android devices. Furthermore it does not support writing of the OIS offset data, which unfortunately seems to be a standard among the Android devices. I tried a few Samsung, LG, Sony, Huawei, OnePlus and Google devices when I started the project in 2020. While a few supported OIS On/Off, I found that only the Google Pixel supported both features. It may be different in modern phones.

Depending on the project this may not be a problem. The adjustments are very small and for moderate precision reconstructions I don't think it will have any effect since the offsets are small and the optimizer may approximately adjust for it in the orientation estimate of the camera pose. For high precision reconstructions you may want to estimate the intrinsic camera offset parameters for each frame during the bundling optimization.

**Comment by DavidGillsjo** [comment]
Please reopen the issue if you have any further problems with this.
